const p = new Promise(resolve, reject);
p.then((result) => console.log(result)).catch((err) => console.log(err));
